joint1_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint1
  pid:
    p: 5.0
    i: 3.0
    d: 1.0

joint2_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint2
  pid:
    p: 10.0
    i: 5.0 
    d: 1.0

joint3_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint3
  pid:
    p: 5.0
    i: 3.0
    d: 1.0

joint4_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint4
  pid:
    p: 4.0
    i: 1.0
    d: 1.0


