joint1_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint1
  pid:
    p: 10.0
    i: 0
    d: 0.4

joint2_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint2
  pid:
    p: 50.0
    i: 0
    d: 5

joint3_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint3
  pid:
    p: 50.0
    i: 0
    d: 1

joint4_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint4
  pid:
    p: 5.0
    i: 0
    d: 1

joint5_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint5
  pid:
    p: 5.0
    i: 0
    d: 1

joint6_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint6
  pid:
    p: 5.0
    i: 0
    d: 1


