joint1_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint1
  pid:
    p: 1.0
    i: 1
    d: 1

joint2_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint2
  pid:
    p: 1.0
    i: 1 
    d: 1

joint3_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint3
  pid:
    p: 1.0
    i: 1
    d: 1

joint4_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: joint4
  pid:
    p: 1.0
    i: 1
    d: 1


