<?xml version="1.0"?>

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	  xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <!-- Properties (Constants) -->
  <xacro:property name="M_PI" value="3.14159" />

  <xacro:property name="wheel_radius" value="0.073" />
  <xacro:property name="wheel_size_y" value="0.09" />
  <xacro:property name="wheel_offset_x" value="0.16" />
  <xacro:property name="wheel_offset_y" value="0.155" /> <!-- half of wheel width + half of socket width + gap -->
  <xacro:property name="wheel_offset_z" value="-0.112" /> <!-- wheel_radius - socket height -->

  <xacro:macro name="hector_wheel" params="parent prefix suffix reflect_x reflect_y wheel_joint_type">

    <joint name="${prefix}_${suffix}_steering_joint" type="revolute">
      <origin xyz="${wheel_offset_x * reflect_x} ${wheel_offset_y * reflect_y} ${wheel_offset_z}" rpy="0 0 0" />
      <parent link="${parent}" />
      <child link="${prefix}_${suffix}_motor_link" />
      <axis xyz="0 0 1" />
      <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="100" velocity="100" />
      <!--<mimic joint="steer${prefix}" multiplier="1.234" offset="0.0" />-->
    </joint>

<!--    <joint name="${prefix}_${suffix}_motor_joint" type="fixed">
      <origin xyz="${wheel_offset_x * reflect_x} ${wheel_offset_y * reflect_y} ${wheel_offset_z}" rpy="0 0 0" />
      <parent link="${parent}" />
      <child link="${prefix}_${suffix}_motor_link" />
    </joint> -->

    <link name="${prefix}_${suffix}_motor_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz=" 0 0 0 " />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01" />
      </inertial>

      <visual>
        <origin xyz="0 ${reflect_y*(wheel_size_y/2 + 0.01)*-1} 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="0.004" length="0.02"/>
        </geometry>
        <material name="Red" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="0.007" length="${wheel_size_y + 0.01}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_${suffix}_wheel_joint" type="${wheel_joint_type}">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="100" />
      <dynamics damping="0.0" friction="0.0" />
      <parent link="${prefix}_${suffix}_motor_link" />
      <child link="${prefix}_${suffix}_wheel_link" />
    </joint>

    <link name="${prefix}_${suffix}_wheel_link">
      <inertial_sphere mass="0.2" diameter="0.14" />
      <visual>
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_size_y}"/>
        </geometry>
        <material name="Black" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_size_y}" />
        </geometry>
        <material name="MTWheelColMat"/>
      </collision>
    </link>

    <gazebo reference="${prefix}_${suffix}_wheel_link" >
      <mu1 value="1.0" />
      <mu2 value="1.0" />
      <kp  value="100000.0" />
      <kd  value="1.0" />
      <material>Hector/Grey</material>
    </gazebo>

    <gazebo reference="${prefix}_${suffix}_motor_link" >
      <material>Hector/White</material>
    </gazebo>

    <transmission type="pr2_mechanism_model/SimpleTransmission" name="${prefix}_${suffix}_wheel_trans">
      <actuator name="${prefix}_${suffix}_motor_link" />
      <joint name="${prefix}_${suffix}_wheel_joint" />
      <mechanicalReduction>1.0</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </transmission>

    <transmission type="pr2_mechanism_model/SimpleTransmission" name="${prefix}_${suffix}_steering_trans">
      <actuator name="${parent}" />
      <joint name="${prefix}_${suffix}_steering_joint" />
      <mechanicalReduction>${reflect_x}</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </transmission>

  </xacro:macro>
</robot>

