<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
name="biorob_ultra_x5_hg_as_x4">

  <xacro:property name="base_height" value=".008"/>
  <xacro:property name="j1_length" value=".276"/>
  <!--0.284 to base plate-->
  <xacro:property name="j2_length" value=".305"/>
  <xacro:property name="j3_length" value=".305"/>
  <xacro:property name="j4_length" value=".167"/>
  <xacro:property name="pi" value="3.1415926536"/>
  
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </xacro:macro>
  
  <macro name="biorob_ultra_x5_hg_as_x4_arm" params="parent *origin">
    <link name="biorob_base_link">
      <visual>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_0.dae"/>
          <!--<cylinder radius="${base_radius}" length="${base_height}"/>-->
        </geometry>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <material name="blue">
          <color rgba="0 0 .8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <!--<cylinder radius="${base_radius}" length="${base_height}"/>-->
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_0.dae"/>
        </geometry>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      </collision>
      <xacro:default_inertial mass="0.1"/>
    </link>
    <gazebo reference="biorob_base_link">
      <selfCollide>true</selfCollide>
      <material>biorob_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="biorob_link1">
      <visual>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_1.dae"/>
          <!--                    <box size="${j1_x} ${j1_y} ${j1_z}" />-->
        </geometry>
        <origin xyz="0 0 ${-base_height}" rpy="0 0 ${pi/2}"/>
        <material name="green">
          <color rgba="0.9 0.9 0.9 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_1.dae"/>
          <!--<box size="${j1_x} ${j1_y} ${j1_z}" />-->
        </geometry>
        <origin xyz="0 0 ${-base_height}" rpy="0 0 ${pi/2}"/>
      </collision>
      <xacro:default_inertial mass="3"/>
    </link>
    <gazebo reference="biorob_link1">
      <selfCollide>true</selfCollide>
      <material>biorob_material/White</material>
      <!--<material>Gazebo/Blue</material>-->
    </gazebo>
    <link name="biorob_link2">
      <visual>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_2.dae"/>
          <!--<mesh filename="package://katana_description/meshes/katana/katana_internal_controlbox.stl" />-->
        </geometry>
        <!--<origin xyz="${j2_length/2 - j2_overhang_rear/2 } 0 0" rpy="0 ${pi/2} 0"/>-->
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi}"/>
        <material name="red">
          <color rgba="0.6 0.6 0.6 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_2.dae"/>
          <!--<cylinder radius="0.02" length="${j2_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi}"/>
      </collision>
      <xacro:default_inertial mass="0.5"/>
    </link>
    <gazebo reference="biorob_link2">
      <selfCollide>true</selfCollide>
      <material>biorob_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="biorob_link3">
      <visual>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_3.dae"/>
          <!--<cylinder radius="0.02" length="${j3_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <material name="red">
                  
                </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_3.dae"/>
          <!--  <cylinder radius="0.02" length="${j3_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      </collision>
      <xacro:default_inertial mass="0.1"/>
    </link>
    <gazebo reference="biorob_link3">
      <selfCollide>true</selfCollide>
      <material>biorob_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="biorob_link4">
      <visual>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_4.dae"/>
          <!--  <cylinder radius="0.02" length="${j4_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <material name="red">
                  
                </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://biorob_description/meshes/biorob_common/biorob_link_4.dae"/>
          <!--<cylinder radius="0.02" length="${j4_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      </collision>
      <xacro:default_inertial mass="0.1"/>
    </link>
    <gazebo reference="biorob_link4">
      <selfCollide>true</selfCollide>
      <material>biorob_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="biorob_toolframe">
      <visual>
        <geometry>
          <cylinder radius="0.01" length="0.001" />
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <material name="red">                  
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.02" length="0.001" />
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      </collision>
      <xacro:default_inertial mass="0.05"/>
    </link>
    
    <joint name="biorob_base_joint" type="fixed">
      <insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="biorob_base_link"/>
    </joint>
    <joint name="joint1" type="revolute">
      <parent link="biorob_base_link"/>
      <child link="biorob_link1"/>
      <axis xyz="0 0 1"/>
      <origin xyz="0 0 ${base_height}"/>
      <limit effort="6.0" lower="${-pi*(140/180)}" upper="${pi*(140/180)}" velocity="1.5708"/>
      <!-- TODO: give correct effort limits -->
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <joint name="joint2" type="revolute">
      <parent link="biorob_link1"/>
      <child link="biorob_link2"/>
      <axis xyz="0 0 1"/>
      <origin xyz="0 0 ${j1_length}" rpy="${pi/2} 0 0"/>
      <limit effort="6.0" lower="${-pi*(170/180)}" upper="${pi*(170/180)}" velocity="1.5708"/>
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <joint name="joint3" type="revolute">
      <parent link="biorob_link2"/>
      <child link="biorob_link3"/>
      <axis xyz="0 0 1 "/>
      <origin xyz="0 ${j2_length} 0" rpy="0 0 ${pi/2}"/>
      <limit effort="6.0" lower="${-pi*(100/180)}" upper="${pi*(100/180)}" velocity="1.5708"/>
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <joint name="joint4" type="revolute">
      <parent link="biorob_link3"/>
      <child link="biorob_link4"/>
      <axis xyz="0 0 1"/>
      <origin xyz="${j3_length} 0 0.0"/>
      <limit effort="6.0" lower="${-pi*(100/180)}" upper="${pi*(100/180)}" velocity="1.5708"/>
      <!-- TODO: give correct effort limits -->
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <joint name="tool_frame" type="fixed">
      <parent link="biorob_link4"/>
      <child link="biorob_toolframe"/>
      <axis xyz="0 0 1"/>
      <origin xyz="${j4_length} 0.0 0.0" rpy="0 0 0"/>
    </joint>
    
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="joint1_trans">
      <actuator name="joint1_motor"/>
      <joint name="joint1"/>
      <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="joint2_trans">
      <actuator name="joint2_motor"/>
      <joint name="joint2"/>
      <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="joint3_trans">
      <actuator name="joint3_motor"/>
      <joint name="joint3"/>
      <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="joint4_trans">
      <actuator name="joint4_motor"/>
      <joint name="joint4"/>
      <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    
<!--    <gazebo reference="biorob_toolframe">
      <sensor:camera name="finger_tip_camera_sensor">
        <imageSize>640 480</imageSize>
        <imageFormat>R8G8B8</imageFormat>
        <hfov>90</hfov>
        <nearClip>0.01</nearClip>
        <farClip>100</farClip>
        <updateRate>20.0</updateRate>
        <controller:gazebo_ros_camera name="finger_tip_camera_controller" plugin="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <imageTopicName>finger_tip_cam/image</imageTopicName>
          <frameName>biorob_toolframe</frameName>
          <interface:camera name="finger_tip_camera_iface"/>
        </controller:gazebo_ros_camera>
      </sensor:camera>
      <turnGravityOff>true</turnGravityOff>
      <material>PR2/Blue</material>
    </gazebo>
    <gazebo>
      <controller:gazebo_ros_controller_manager name="gazebo_ros_controller_manager" plugin="libgazebo_ros_controller_manager.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <interface:audio name="gazebo_ros_controller_manager_dummy_iface_biorob"/>
      </controller:gazebo_ros_controller_manager>
    </gazebo>-->
  </macro>
</robot>
